import {
  LABEL_SUGGESTIONS as LLM_LABEL_SUGGESTIONS,
  LABEL_SKIP as LLM_LABEL_SKIP,
} from "./constants-llm-generated.js";

// prettier-ignore
export const SPAM_USERS = new Set([
  44313, 124302, 25191, 16441, 83215, 88617, 144709, 50096, 151428, 91848,
  92994, 15438, 80251, 110107, 84966, 61102, 69617, 135237, 147329, 13272,
  68271, 124421, 145, 2235, 2399, 4304, 5602, 6413, 6441, 6503, 6507, 6514,
  7840, 11721, 11732, 12779, 12802, 13263, 13563, 13904, 14481, 17694, 17936,
  20149, 21139, 23526, 23648, 23746, 24201, 24518, 26913, 27895, 28554, 31242,
  33307, 39465, 41476, 41713, 41824, 42773, 43119, 44514, 48359, 50459, 50504,
  52952, 53650, 57007, 58171, 59557, 60731, 60996, 63054, 63094, 65892, 66516,
  67206, 71179, 71795, 72134, 72562, 74529, 74781, 75120, 75731, 76093, 77411,
  79676, 79981, 80906, 82370, 82948, 84006, 84299, 86175, 86456, 89440, 89653,
  94383, 94940, 95299, 96362, 96705, 98500, 99259, 99623, 99736, 100214, 104093,
  104432, 108167, 108432, 108546, 108723, 110457, 112702, 114058, 114913,
  115367, 115472, 116380, 116718, 116751, 117006, 117711, 122887, 123360,
  124857, 129330, 130822, 131014, 133745, 134542, 134671, 134675, 134686,
  134696, 134703, 134717, 134730, 134754, 135249, 135690, 137051, 137928,
  138961, 141188, 142310, 142637, 144191, 145604, 147029, 147615, 149113,
  149656, 150537, 151239, 151482, 151814, 66676, 125994, 143153, 90920, 94414,
  65667,
  69543,126322,
  65273,
  119425, // puts blue for most answers
  115090, // identified as always providing wrong colors
  3429,
  14284,
  15466,
  15806,
  70886,129843,68508,126077,29856,30118,
  38,10720,
  144285,
  65870,
  67993,
  77266,
  78729,
  80405,
  88993,
  105286,
  114470,
  119171,118796,131922,145624,149717,151431,
  33012,
  4095,8204,14467,19016,

  // response is likely non-english
  1772,2137,2413,6395,8052,10313,11977,12460,16417,17380,17993,19236,24839,25000,
  25007,28147,28942,29701,32581,34134,34526,34637,35509,35874,40593,40989,42570,
  46098,46145,50144,50363,50666,50941,53012,55029,56770,56920,57464,58418,63104,65084,
  67087,68823,69090,71081,81723,83391,83606,86282,87853,89979,90578,93080,93629,95531,
  96266,97728,100678,103862,107527,107674,112313,115113,117370,117560,117578,117982,
  118252,119742,122248,125604,125785,127189,127353,129685,135232,136106,137476,138880,140124,
  144208,147202,147520,147667,148169,148392,148941,150274,150575,150798,

  // users who repeated the majority of their labels like just putting "green" over and over
  3946,15879,16182,17071,19008,19589,21427,21445,22303,
  22442,22655,23542,23983,24659,26153,29029,32001,34724,
  35553,35797,36016,36028,37390,37503,41365,41488,42096,
  46203,51142,54608,54683,55159,55292,56739,60345,62110,62374,
  62450,63820,63824,64366,64566,67002,69822,75498,77211,77499,
  78249,79395,79712,80327,80594,81108,83175,88143,90569,91262,
  91746,91902,94809,95060,95695,99046,102343,103344,105961,105984,
  106157,106650,106877,109818,109871,110618,110743,112519,114547,
  114858,116358,116994,118621,119346,119413,121626,121650,121848,
  121973,123686,124178,125112,125426,126153,127708,128258,128614,
  129946,130803,130956,132788,132852,133054,134362,135582,135665,
  136245,136713,138849,139775,141536,141999,143637,146170,146202,
  146735,147001,147578,149233,150245,150633,151716,151805,18506,73232,
  101922,114704,18630,54011,100561,102817,105638,143630,145643,147690,
  17949,80632,82487,111041,146771,146742,12994,111041,100592,
  80953,101431,

  // users who had 7+ votes but missed 75% of centroids by a huge margin of OKLab delta error
  75267,100997,117438,126938,131243,131370,145360,146211,139311,139015,64301,56356,62783,137389,
  52364,137689,38237,67035,19099,144043,38844,68489,138100,

  // users who had 5+ votes but missed 100% of centroids by a huge margin of error
  3396,28755,39675,46354,58909,92575,95418,100925,137829,

  // this user has ~200 records but many of them are clear trolls, although some are decent
  65012,

  // a lot of users seem to give up halfway through answering and just put the same label over and over
  // it would be better to capture the 'give up' point and only take the early records
  29006,
]);

export const DECENT_LONG_NAMES = new Set([
  // ultra long
  "light blue with a hint of green",
  "some kind of purple",
  "blue with some purple",
  "another shade of purple",
  "slightly darker light green",
  "very very light green",
  "light green with a hint of blue",
  "somewhere between blue and purple",
  "light robins egg blue",
  "very very light blue",
  "green with some yellow",
  "dark blue with a hint of purple",
  "light green with a hint of yellow",
  "teenage mutant ninja turtle green",
  "something between blue and purple",
  "kermit the frog green",
  "some kind of blue",
  "yet another green",
  "yet another blue",
  "yet another purple",
  "barney the dinosaur purple",
  // others with >= 4 tokens
  "dark robin egg blue",
  "blue screen of death",
  "light sea foam green",
  "bright sea foam green",
  "bright robin egg blue",
  // these appear >= 4 times
  "dark sea foam green",
  "forget me not blue",
  "dark robins egg blue",
  "split pea soup green",
  "granny smith apple green",
  "bright robins egg blue",
  "blue screen of death blue",
  "key lime pie green",
  "screen of death blue",
  "st patricks day green",
  "post it note yellow",
  "slightly darker lime green",
  "not quite olive green",
  "apple blue sea green",
  "blue with a bit of green",
  "very dark olive green",
  "dark green forest green",
  "hurts my eyes pink",
  "red with a hint of purple",
  "green with hint of blue",
  "very dark blue green",
  "yellow with a tint of green",
  "between blue and purple",
  "blue with a little red",
  "blue with a hint of violet",
  "gray with a hint of pink",
  "not so dark green",
  "very very dark blue",
  "pink with a little purple",
  "dark gray green blue",
  "yellow with a tinge of green",
  "very very dark green",
  "my little pony purple",
  "purple with a hint of blue",
  "very very dark purple",
  "yet another shade of green",
  "white with a hint of blue",
  "blue with purple tinge",
  "gray with a tint of purple",
  "blue with a little green",
  "yellow with a green tinge",
  "in your face blue",
  "green with a hint of brown",
  "blue with a touch of violet",
  "slightly less dark purple",
  "lighter than navy blue",
  "red with a touch of pink",
  "post it note blue",
  "really really dark green",
  "not quite royal blue",
  "yellow with a green tint",
  "darker than lime green",
  "purple with a hint of gray",
  "gray with a tinge of green",
  "dark dark dark blue",
  "gray with hint of blue",
  "its a boy blue",
  "gray with a tinge of blue",
  "hard boiled egg yolk yellow",
  "macaroni and cheese orange",
  "blue with a purple tint",
  "pink with a touch of purple",
  "gray with a tint of blue",
  "blue with a tint of purple",
  "poison dart frog green",
  "very dark navy blue",
  "between green and blue",
  "dark duck egg blue",
  "blue with a purple tinge",
  "ms paint sky blue",
  "dark dark dark green",
  "gray with a little blue",
  "lighter shade of blue",
  "gray with a bit of green",
  "mint ice cream green",
  "brown with a hint of purple",
  "green with a hint of gray",
  "green with a tinge of blue",
  "green tea ice cream",
  "blue with a touch of red",
  "blue with hints of purple",
  "dark blue with gray",
  "its a girl pink",
  "blue with a bit of gray",
  "blue with a tint of green",
  "artificial grape flavor purple",
  "macaroni and cheese yellow",
  "brown with a hint of yellow",
  "video game grass green",
  "slightly less royal blue",
  "not quite mint green",
  "dark blue green gray",
  "late afternoon sky blue",
  "slightly less dark green",
  "washed out navy blue",
  "between purple and blue",
  "lighter than dark blue",
  "black like my soul",
  "ow my eyes pink",
  "gray with a tinge of purple",
  "green with a tinge of yellow",
  "yellow with a hint of brown",
  "my little pony pink",
  "dark green with blue",
  "blue with a touch of green",
  "green eggs and ham",
  "slightly less bright green",
  "red with a little pink",
  "red with a bit of pink",
  "gray with hint of purple",
  "dark purple royal purple",
  "red with a bit of orange",
  "dark gray blue green",
  "not so dark purple",
  "very dark forest green",
  "purple with a lot of blue",
  "darker than usual green",
  "saturated robins egg blue",
  "blue with a tinge of green",
  "gray with a tint of green",
  "blue verging on purple",
  "red with a touch of purple",
  "gray with a blue tint",
  "washed out lime green",
  "pink with a dash of purple",
  "in your face purple",
  "green with a touch of yellow",
  "dark gray or black",
  "pink with a touch of blue",
  "bit darker than sky blue",
  "green mixed with white",
  "sea foam blue green",
  "not so bright green",
  "dark dark dark purple",
  "washed out dark green",
  "different shade of green",
  "dark blue with a hint of gray",
  "blue like crayola marker blue",
  "blue with a grayish tint",
  "video game sky blue",
  "between green and yellow",
  "not so dark blue",
  "lighter than sky blue",
  "brown with green tinge",
  "somewhere between red and pink",
  "dark dark dark brown",
  "hurt your eyes green",
  "green with a little yellow",
  "very bright lime green",
  "between red and pink",
  "lighter sea foam green",
  "very very dark gray",
  "dark dark dark pink",
  "mac os 9 blue",
  "gray with a little bit of blue",
  "orange with a hint of red",
  "purple with a hint of red",
  "purple with a bit of pink",
  "deep sea foam green",
  "hurt my eyes green",
  "brown with a touch of red",
  "strawberry ice cream pink",
  "st pattys day green",
  "brown with a little red",
  "way too bright green",
  "gray with green tint",
  "deep robins egg blue",
  "gray with a hint of violet",
  "pink with a tinge of purple",
  "green with a blue tinge",
  "gray with hint of green",
  "pink with a hint of orange",
  "lime green neon green",
  "sort of sky blue",
  "green with blue tint",
  "gray with a bit of blue",
  "slightly darker baby blue",
  "windows 2000 desktop blue",
  "green with blue tones",
  "dark green almost black",
  "granny apple smith green",
  "not so deep purple",
  "white with a hint of green",
  "green with a tint of yellow",
  "black with a hint of brown",
  "pink with a purple tint",
  "blue with a hint of lavender",
  "red with a hint of blue",
  "super mario sky blue",
  "royal blue screen of death",
  "green with a blue tint",
  "green blue with more green",
  "yellow with hint of green",
  "darker sea foam green",
  "blue hint of purple",
  "green with a hint of lime",
  "80s pop star eyeshadow",
  // hints and tints - maybe worth keeping?
  "blue with a hint of purple", // comes up 124 times!
  "green with a hint of blue",
  "yellow with a hint of green",
  "gray with a hint of blue",
  "gray with a hint of green",
  "gray with a hint of purple",
  "blue with a hint of green",
  "blue with a hint of gray",
  "green with a bit of blue",
  "blue with a bit of purple",
  "red with a hint of pink",
  "green with a hint of yellow",
  "not quite sky blue",
  "gray with a hint of brown",
  "yellow with a bit of green",
  "blue with a little purple",
  "not quite lime green",
  "gray with a hint of red",
  "brown with a hint of green",
  "blue with a tinge of purple",
  "slightly darker sky blue",
  "not quite navy blue",
  "purple with a hint of pink",
  "darker than sky blue",
  "green with a little blue",
  "yellow with a touch of green",
  "pink with a hint of purple",
  "blue with a touch of purple",
  "not so hot pink",
  "blue with a touch of gray",
  "green with a touch of blue",
  "blue with a hint of red",
  "between pink and purple",
  "gray with a touch of blue",
  "slightly darker than sky blue",
  "brown with a hint of red",
  "green with a bit of yellow",
  "yet another shade of blue",
  "blue with hint of purple",
  "red with a hint of orange",
  "dark green with a hint of blue",
  "gray with a touch of green",
  "green with a tint of blue",
  "blue with a little gray",
  "red with a hint of brown",
]);

export const TYPO_MAP = new Map([
  ["browrange", "brorange"],
  ["gray pupon", "gray poupon"], // it will be converted to grey at end
  ["emerals", "emerald"],
  ["hoovooloo", "hooloovoo"],
  ["palish", "paleish"],
  ["tarheel", "tar heel"],
  ["trex green", "t rex green"],
  ["hooker green", "hookers green"],
  ["dark aqua marine", "dark aquamarine"],
  ["aqua marine green", "aquamarine green"],
  ["aqua marine", "aquamarine"],
  ["purplie", "purply"],
  ["lavender ish", "lavenderish"],
  ["supergreen", "super green"],
  ["koolaid", "kool aid"],
  ["peptobismol", "pepto bismol"],
  ["peptobismal", "pepto bismol"],
  ["pepto bismal", "pepto bismol"],
  ["pinetree", "pine tree"],
  ["dunkelblau", "dark blue"],
  ["grimmace purple", "grimace purple"],
  ["vermillion", "vermilion"],
  ["gren", "green"],
  ["mspaint", "ms paint"],
  ["robins", "robin"],
  ["doodoo", "doo doo"],
  ["puple", "purple"],
  ["purble", "purple"],
  ["faun", "fawn"],
  ["algea", "algae"],
  ["bsod", "blue screen of death"], // normalise to longer form
  ["ble", "blue"], // guess it could mean wheat in french?
  ["verde", "green"], // another one that ends up with basically duplicate oklab
  ["bluegreen", "blue green"],
  ["ping", "pink"],
  ["lightblue", "light blue"],
  ["lightpurple", "light purple"],
  ["grey", "gray"],
  ["yello", "yellow"],
  ["marron", "maroon"],
  ["purplr", "purple"],
  ["lightpink", "light pink"],
  ["limish", "limeish"],
  ["orang", "orange"],
  ["grn", "green"],
  ["grenn", "green"],
  ["pnk", "pink"],
  ["bue", "blue"],
  ["fluo", "fluorescent"],
  ["amythest", "amethyst"],
  ["flouro", "fluorescent"],
  ["purlpe", "purple"],
  ["orage", "orange"],
  ["lue", "blue"],
  ["beigh", "beige"],
  ["baige", "beige"],
  ["bege", "beige"],
  ["maube", "mauve"],
  ["militar", "military"],
  ["bluye", "blue"],
  ["urple", "purple"],
  ["bluw", "blue"],
  ["cian", "cyan"],
  ["chartreux", "chartreuse"],
  ["blueish", "bluish"], // ...
  ["blueishgreen", "bluish green"],
  ["turquoiseish", "turquoisish"], // normalize
  ["purpleish", "purplish"], //
  ["greenscreen", "green screen"],
  ["purple ish", "purplish"], //
  ["purple ish blue", "purplish blue"], //
  ["purple ish pink", "purplish pink"], //
  ["purple ish gray", "purplish gray"],
  ["purple ish red", "purplish red"],
  ["purple ish brown", "purplish brown"],
  ["magentish", "magentaish"],
  ["ocker", "ochre"],
  ["purp", "purple"],
  ["pruple", "purple"],
  ["gret", "gray"],
  ["blu", "blue"],
  ["pumpernickle", "pumpernickel"],
  ["pink dark", "dark pink"], // normalize a few
  ["green pale", "pale green"],
  ["yellow dark", "dark yellow"],
  ["red dark", "dark red"],
  ["browm", "brown"],
  ["forrest", "forest"],
  ["matt", "matte"],
  ["yelloe", "yellow"],
  ["moroon", "maroon"],
  ["greay", "gray"],
  ["gras", "grass"],
  ["gree", "green"],
  ["vioet", "violet"],
  ["lt blue", "light blue"],
  ["blakc", "black"],
  ["creame", "cream"],
  ["grreen", "green"],
  ["vlue", "blue"],
  ["dk", "dark"],
  ["grat", "gray"],
  ["diarrhoea", "diarrhea"],
  ["diahrea", "diarrhea"],
  ["vilet", "violet"],
  ["yeloow", "yellow"],
  ["cobolt", "cobalt"],
  ["magena", "magenta"],
  ["tel", "teal"],
  ["skin colour", "skin"], // we will later strip entries with 'color' as it's often "ugly color" etc.
  ["flesh color", "flesh"], // same reason
  ["flesh colour", "flesh"], // same reason
  ["taup", "taupe"],
  ["brwn", "brown"],
  ["res", "red"],
  ["pinnk", "pink"],
  ["chartreuce", "chartreuse"],
  ["prange", "orange"], //assumed
  ["greenm", "green"],
  ["pinik", "pink"], // assumed
  ["oarnge", "orange"],
  ["mauv", "mauve"],
  ["orance", "orange"],
  ["gery", "gray"],
  ["perywinkle", "periwinkle"],
  ["lt", "light"],
  ["pikn", "pink"],
  ["bkue", "blue"],
  ["nlue", "blue"],
  ["lightgreen", "light green"],
  ["majenta", "magenta"],
  ["skyblue", "sky blue"],
  ["purpl", "purple"],
  ["fucisa", "fuchsia"],
  ["chartruesse", "chartreuse"],
  ["middleblue", "middle blue"],
  ["oceangreen", "ocean green"],
  ["verdent", "verdant"],
  ["darkergreen", "darker green"],
  ["torquoise", "turquoise"],
  ["tyrquoise", "turquoise"],
  ["pulpre", "purple"],
  ["pomigranite", "pomegranate"],
  ["lavendar", "lavender"],
  ["darkblue", "dark blue"],
  ["torquise", "turquoise"],
  ["turkoise", "turquoise"],
  ["cya", "cyan"],
  ["fusha", "fuchsia"],
  ["fuschsia", "fuchsia"],
  ["fuchisa", "fuchsia"],
  ["fuisha", "fuchsia"],
  ["tan ish", "tannish"],
  ["fucsia", "fuchsia"],
  ["turquois", "turquoise"],
  ["turquiose", "turquoise"],
  ["tourquoise", "turquoise"],
  ["turquise", "turquoise"],
  ["read", "red"],
  ["turquis", "turquoise"],
  ["lavander", "lavender"],
  ["avacado", "avocado"],
  ["maganta", "magenta"],
  ["purpley", "purply"], // kinda subjective?
  ["purpely", "purply"],
  ["redish", "reddish"],
  ["flourescent", "fluorescent"],
  ["muave", "mauve"],
  ["liliac", "lilac"],
  ["fuschsia", "fuchsia"],
  ["brownishgreen", "brownish green"],
  ["marone", "maroon"],
  ["lila", "lilac"],
  ["bllue", "blue"],
  ["lite purple", "light purple"],
  ["lite green", "light green"],
  ["lite blue", "light blue"],
  ["borwn", "brown"],
  ["biege", "beige"],
  // salmon vs salmon pink?
  // olive vs olive green?
  ["fuschia", "fuchsia"],
  ["fuscha", "fuchsia"],
  ["fucshia", "fuchsia"],
  ["fuchsia sp", "fuchsia"],
  ["purpe", "purple"],
  ["purle", "purple"],
  ["purpel", "purple"],
  ["rasperry", "raspberry"],
  ["voilet", "violet"],
  ["florescent", "fluorescent"],
  ["ornage", "orange"],
  ["teracotta", "terracotta"],
  ["terra cota", "terracotta"],
  ["burt orange", "burnt orange"],
  ["magneta", "magenta"],
  ["greeen", "green"],
  ["fuchia", "fuchsia"],
  ["fusia", "fuchsia"],
  ["fucia", "fuchsia"],
  ["bleu", "blue"],
  ["fushcia", "fuchsia"],
  ["fuscia", "fuchsia"],
  ["thalo", "phthalo"],
  ["sea foam green", "seafoam green"],
  ["kelley green", "kelly green"],
  ["kahki", "khaki"],
  ["burgandy", "burgundy"],
  ["toupe", "taupe"],
  ["sea foam", "seafoam"],
  ["golden rod", "goldenrod"],
  ["peuce", "puce"],
  ["camoflage", "camouflage"],
  ["greenblue", "green blue"],
  ["tope", "taupe"],
  ["kaki", "khaki"],
  ["fushia", "fuchsia"],
  ["seagreen", "sea green"],
  ["purlple", "purple"],
  ["bordeau", "bordeaux"],
  ["bllue", "blue"],
  ["borwn", "brown"],
  ["perriwinkle", "periwinkle"],
  ["oramge", "orange"],
  ["saphire", "sapphire"],
  ["ocre", "ochre"],
  ["ocher", "ochre"],
  ["paleblue", "pale blue"],
  ["darkslategray", "dark slate gray"],
  ["burgundry", "burgundy"],
  ["mossy green", "moss green"],
  ["sage green", "sage"],
  ["flesh tone", "flesh"],
  ["redish brown", "reddish brown"],
  ["burnt siena", "burnt sienna"],
  ["creme", "cream"],
  ["teel", "teal"],
  ["gray ish green", "grayish green"],
  ["greengrey", "green gray"],
  ["greygreen", "gray green"],
  ["greyish", "grayish"],
  ["pink ish", "pinkish"],
  ["blue ish", "bluish"],
  ["perrywinkle", "periwinkle"],
  ["terracota", "terracotta"],
  ["greyblue", "grayblue"],
  ["pistacchio", "pistachio"],
  ["bluegrey", "bluegray"],
  ["chartruse", "chartreuse"],
  ["grean", "green"],
  ["sea grean", "sea green"],
  ["terra cotta ", "terracotta"],
  ["chartruese", "chartreuse"],
  ["marroon", "maroon"],
  ["yellowgray", "yellow gray"],
  ["turquorise", "turquoise"],
  ["mustrad", "mustard"],
  ["turqouoise", "turquoise"],
  ["turqoisey", "turquoisey"],
  ["turquoisy", "turquoisey"],
  ["mahogony", "mahogany"],
  ["turqouise", "turquoise"],
  ["bluegrayish", "blue grayish"],
  ["burgendy", "burgundy"],
  ["babypink", "baby pink"],
  ["asphault", "asphalt"],
  ["windows blue", "windows xp blue"],
  ["tuape", "taupe"],
  ["chartruce", "chartreuse"],
  ["yellowgreen", "yellow green"], // could be separate..
  ["cornflower blue", "cornflower"],
  ["green again", "green"], // :)
  ["greem", "green"],
  ["neongreen", "neon green"],
  ["violett", "violet"],
  ["turqoise", "turquoise"],
  ["greeb", "green"],
  ["darkgreen", "dark green"],
  ["turquesa", "turquoise"], // spanish/portugese :)
  ["orangered", "orange red"],
  ["puse", "puce"], // could be pus or puce, think its probably puce?
  ["oragne", "orange"],
  ["ornage", "orange"],
  ["puprle", "purple"],
  ["pueple", "purple"],
  ["lillac", "lilac"],
  ["magent", "magenta"],
  ["grene", "green"],
  ["blue ish gray", "bluish gray"],
  ["lite blue", "light blue"],
  ["purpule", "purple"],
  ["cerulian", "cerulian"],
  ["brwon", "brown"],
  ["indego", "indigo"],
  ["lylac", "lilac"],
  ["colbalt", "cobalt"],
  ["turqois", "turquoise"],
  ["turquose", "turquoise"],
  ["terquoise", "turquoise"],
  ["tuquoise", "turquoise"],
  ["turqoiuse", "turquoise"],
  ["turquoize", "turquoise"],
  ["torqoise", "turquoise"],
  ["turqouis", "turquoise"],
  ["turqiouse", "turquoise"],
  ["turquios", "turquoise"],
  ["turqiose", "turquoise"],
  ["turqouse", "turquoise"],
  ["camoflauge", "camouflage"],
  ["cammo", "camo"],
  ["mouve", "mauve"],
  ["tanish", "tannish"],
  ["maroone", "maroon"],
  ["bloodred", "blood red"],
  ["ligth", "light"],
  ["siena", "sienna"],
  ["tourquise", "turquoise"],
  ["beigy", "beigey"],
  ["purpple", "purple"],
  ["turcoise", "turquoise"],
  ["blau", "blue"], // a little subjective?
  ["charteuse", "chartreuse"],
  ["megenta", "magenta"],
  ["samon", "salmon"],
  ["yelow", "yellow"],
  ["magent", "magenta"],
  ["acqua", "aqua"],
  ["bluee", "blue"],
  ["bronw", "brown"],
  ["broen", "brown"],
  ["winered", "wine red"],
  ["puice", "puce"],
  ["ligh blue", "light blue"],
  ["orane", "orange"],
  ["ligh green", "light green"],
  ["greeeen", "green"],
  ["plurple", "purple"],
  ["organge", "orange"],
  ["tourqoise", "turquoise"],
  ["turquioise", "turquoise"],
  ["tiel", "teal"],
  ["chartrusse", "chartreuse"],
  ["coloured", "colored"], // normalize
  ["colour", "color"], // normalize
  ["pik", "pink"],
  ["pinl", "pink"],
  ["organe", "orange"],
  ["watermellon", "watermelon"],
  ["bordo", "bordeaux"], // maybe presumptuous of me..
  ["purplw", "purple"],
  ["braun", "brown"],
  ["brow", "brown"],
  ["creamcicle", "creamsicle"],
  ["bergandy", "burgundy"],
  ["lawngreen", "lawn green"],
  ["huntergreen", "hunter green"],
  ["aquamrine", "aquamarine"],
  ["lilaac", "lilac"],
  ["bergundy", "burgundy"],
  // ["bright breen", "bright green"], // breen here could be portmanteau?
  ["oliv", "olive"],
  ["fuxia", "fuchsia"],
  ["bron", "brown"],
  ["darkpurple", "dark purple"],
  ["burgondy", "burgundy"],
  ["morone", "maroon"],
  ["safron", "saffron"],
  ["redbrown", "red brown"],
  ["greenn", "green"],
  ["orange y brown", "orangey brown"],
  ["robbins", "robin"],
  ["slamon", "salmon"],
  ["swimmingpool", "swimming pool"],
  ["rasberry", "raspberry"],
  ["cerulian", "cerulean"],
  ["moave", "mauve"],
  ["carribean", "caribbean"],
  ["lavinder", "lavender"],
  ["yelllow", "yellow"],
  ["beighe", "beige"],
  ["maude", "mauve"],
  ["prple", "purple"],
  ["torquiose", "turquoise"],
  ["acquamarine", "quamarine"],
  ["pastle", "pastel"],
  ["celedon", "celadon"],
  ["mangenta", "magenta"],
  ["charcol", "charcoal"],
  ["ligh", "light"],
  ["puece", "puce"],
  ["chartreusse", "chartreuse"],
  ["limegreen", "lime green"],
  ["scarlett", "scarlet"],
  ["lightpurple", "light purple"],
  ["lightbrown", "light brown"],
  ["purpke", "purple"],
  ["mahagony", "mahogany"],
  ["tourqouise", "turquoise"],
  ["purpole", "purple"],
  ["auqua", "aqua"],
  ["florecent", "fluorescent"],
  // ['pinkypurple','pinky purple'],
  ["fuccia", "fuchsia"],
  ["magents", "magenta"],
  ["pomegranite", "pomegranate"],
  ["canteloupe", "cantaloupe"],
  ["cienna", "sienna"],
  ["maron", "maroon"],
  ["fucha", "fuchsia"],
  ["pastell", "pastel"],
  ["mullberry", "mulberry"],
  ["greeeeen", "green"],
  ["chatreuse", "chartreuse"],
  ["karki", "khaki"],
  ["kakhi", "khaki"],
  ["brightgreen", "bright green"],
  ["terra cotta", "terracotta"],
  ["fusica", "fuchsia"],
  ["olivegreen", "olive green"],
  ["pinkey", "pinky"],
  ["yellowey", "yellowy"],
  ["manilla", "manila"],
  ["khakhi", "khaki"],
  ["redy", "reddy"],
  ["limon", "lemon"],
  ["blueviolet", "blue violet"],
  ["greeney", "greeny"],
  ["orangy", "orangey"],
  ["salman", "salmon"],
  ["brightblue", "bright blue"],
  ["orangeish", "orangish"],
  ["teale", "teal"],
  ["ox blood", "oxblood"],
  ["brght", "bright"],
  ["lght", "light"],
  ["prpl", "purple"],
  ["brpwn", "brown"],
  ["plumb", "plum"],
  ["blck", "black"],
  ["veridian", "viridian"],
  ["babyblue", "baby blue"],
  ["seablue", "sea blue"],
  ["aquamarin", "aquamarine"],
  ["perwinkle", "periwinkle"],
  ["sherbert", "sherbet"],
  ["mintgreen", "mint green"],
  ["steelblue", "steel blue"],
  ["auqa", "aqua"],
  ["leafgreen", "leaf green"],
  ["bluie", "bluey"], // normalize?
]);

// after all fixes/cleanup applied, do a full swap on whole label at once
export const SWAP_MAP = new Map([
  ["sea foam blue green", "seafoam blue green"],
  ["lighter sea foam green", "lighter seafoam green"],
  ["deep sea foam green", "deep seafoam green"],
  ["mardi grass purple", "mardi gras purple"],
  ["mardi grass", "mardi gras"],
  ["terra cotta red", "terracotta red"],
  ["prussian", "prussian blue"],
  ["facebook", "facebook blue"],
  ["darkred", "dark red"],
  ["darkpink", "dark pink"],
  ["darkbrown", "dark brown"],
  ["forestgreen", "forest green"],
  ["grassgreen", "grass green"],
  ["navyblue", "navy blue"],
  ["burn orange", "burnt orange"],
  ["airforce blue", "air force blue"],
  ["geen", "green"],
  ["corn flower", "cornflower"],
  ["corn flower blue", "cornflower blue"],
  ["line green", "lime green"],
  ["sprng green", "spring green"],
  // NORMALISATIONS
  ["robins egg blue", "robin egg blue"],
  ["robin eggs blue", "robin egg blue"],
  ["robin eggs blue", "robin egg blue"],
  ["deep robins egg blue", "deep robin egg blue"],
  // ["key lime pie green", "key lime"], // take the shorter and most popular
  // ["barney the dinosaur purple", "barney purple"],
  // ["granny smith apple green", "granny smith apple"],
  ["pale robins egg blue", "pale robin egg blue"],
  ["bright robins egg blue", "bright robin egg blue"],
  ["dark robins egg blue", "dark robin egg blue"],
  // ["bsod blue", "blue screen of death"],
  // ["kermit the frog green", "kermit green"], // normalise to shorter
  // ["forget me not blue", "forget me not"], // could normalise it the other way, but this seems shorter
  ["dark sea foam green", "dark seafoam green"], // could normalise it the other way, but this seems shorter
  // ["baby boy blue", "baby blue"],
  // ["post it note yellow", "post it yellow"], // more popualr
  ["pale sea foam green", "pale seafoam green"],
  // ["st patricks day green", "st patricks day"],
  // ["st patricks green", "st patricks day"],
  ["blue screen of death blue", "blue screen of death"],
  ["screen of death blue", "blue screen of death"],
  ["purple mtns majesty", "purple mountains majesty"],
  ["purple mountains majesty", "purple mountains majesty"],
  ["purple mountain majesty", "purple mountains majesty"],
  // ["mountain majesty", "purple mountains majesty"],
]);

const toIshy = (color, ish = true) => {
  if (color == "blue") return ish ? "bluish" : "bluey";
  if (color == "purple") return ish ? "purplish" : "purply";
  if (color == "gray") return ish ? "grayish" : "gray";
  if (color == "red") return ish ? "redish" : "reddy";
  if (color == "orange") return ish ? "orangish" : "orangey";
  return ish ? `${color}ish` : `${color}y`;
};

const fragmentSet = new Set([
  "green",
  "brown",
  "yellow",
  "blue",
  "purple",
  "gray",
  "pink",
  "red",
  "orange",
]);

for (let f of [...fragmentSet]) {
  fragmentSet.add(toIshy(f, true));
  fragmentSet.add(toIshy(f, false));
}

for (let f0 of fragmentSet) {
  for (let f1 of fragmentSet) {
    const pair = [f0, f1];
    TYPO_MAP.set(pair.join(""), pair.join(" ")); // bluegray -> blue gray
  }
}

// copy over the LLM-generated suggestions
for (let [a, b] of LLM_LABEL_SUGGESTIONS.entries()) {
  TYPO_MAP.set(a, b);
}

// if this term appears anywhere in the phrase (or its the name itself)
// we skip. a lot of filtering to reduce low quality results
export const SKIP_TERMS = new Set([
  "turkish", // ?? its weird
  "turkey", // ?? why are people calling this a color?
  "ochra", // okra or ochre?
  "oker", // same
  "00ff00",
  "also",
  "chinese",
  "bage", // beige..?
  "purpur",
  "homosexual",
  "faggy",
  "homosexuality",
  "fagy",
  "herpes",
  "adf",
  "jesus",
  "oink",
  "greed",
  "roze", // dutch word for pink
  "yourmum",
  "oliva",
  "robert",
  "drak",
  "frank",
  "why",
  "paars", // dutch for purple
  "lilla",
  "gleen",
  "grayn",
  "viole",
  "dfg",
  "adsf",
  "quamarine",
  "derp",
  "josh",
  "pank",
  "drak",
  "blie",
  "hell", // means 'light' apparently, but let's filter it out...
  "hellblau",
  "bley",
  "buttplugs",
  "grayey", // probably means 'grayish' but easier to just skip
  "blure",
  "clue",
  "gween", // green but meh, skip user submission
  "yeller",
  "purps",
  "crappy",
  "terrible",
  "rtzj",
  "xkcd", //
  "grau",
  "wikiluke",
  "babyshit",
  "prink",
  "pick", // just skip the bad pinks
  "pin", // probably pink
  "teak", // actually targets teal ? it's a weird one
  "dunno",
  "ref",
  "ouch",
  "die",
  "gre", // could be green, maybe worth a typo fix?
  "geren", // also could be green..
  "how",
  "pnik",
  "putple",
  "fsd",
  "mohsinkhan",
  "groen", // green?
  "auga", // prob aqua
  "0000ff",
  "dfs",
  "dsa",
  "brun",
  "pur",
  "pirple", // maybe pink/purple? or a spelling? just ignore since so few votes
  "blie",
  "lilas",
  "gayer",
  "cancer",
  "yuk",
  "turkis",
  "dsf",
  "steve",
  "blye",
  "sigh",
  "lame",
  "sal",
  "qwer",
  "terquise",
  "reen",
  "what",
  "bloo",
  "hideous",
  "bown",
  "blech",
  "fds",
  "hiccup", // ??
  "awful",
  "stop",
  "poiple",
  "pinkl",
  "lol",
  "bleh",
  "cockballz",
  "awua",
  "asdf",
  "not sure",
  "bule",
  "freen",
  "dave",
  "grren",
  "fds",
  "aqu", // aqua? who knows
  "idk", // could be interesting to take data around this
  "argh",
  "james",
  "are",
  "wtf",
  "asf",
  "gary", // could just be gray, let's skip tho
  "paul",
  "henry",
  "booty",
  "moo",
  "fuuuuu",
  "hmm",
  "hmmm",
  "tur",
  "gey",
  "ten",
  "uio",
  "bill", // not sure why its so often repeated
  "wierd",
  "okay",
  "just",
  "many",
  "megan", // most likely magenta but a lot of results skew towards gray?
  "your mom",
  "pants",
  "sdf",
  "sdfg",
  "vbn",
  "gfh",
  "now",
  "dfa",
  "spam",
  "fugly",
  "ewww",
  "ros",
  "skip",
  // "diarrhea", // maybe keep
  "fred",
  "hellgrn",
  "gra", // maybe gray? or maybe not?
  "blah",
  "yes",
  "ugh",
  "meh",
  "asd",
  "this",
  "bored",
  "pee",
  "ian",
  "eww",
  "annoying",
  "stupid",
  "something",
  "that",
  "unknown",
  "ewwww",
  "blauw",
  "asfd",
  "saf",
  "four",
  "trkis",
  "there",
  "aids",
  "bryan",
  "dislike",
  "dfgh",
  "offensive", // maybe keep?
  "ads",
  "sss",
  "hell",
  "ghoti",
  "fghj",
  "ert",
  "puck",
  "none",
  "steven",
  "depressing",
  "creepy",
  "wer",
  "not red",
  "pinker",
  "gayer",
  "gay",
  "gayest",
  "another", // could leave it in too, but this is a bit survey-meta
  "blue yet",
  "purple yet",
  // "bad",
]);

// whereas these have to be an exact match to the name
export const SKIP_LABELS = new Set([
  // filter out low quality responses
  // "girly", // included in curated list
  // "manly", // as above
  "gray or gray", // this happens when somebody says "grey or gray" and we normalize to one
  "who knows",
  "graygreenblue",
  "mediumseagreen",
  "sad", // too ambiguous?
  "nice",
  "nasty",
  "hot",
  "the runs",
  "the blue",
  "the sky",
  "the yellow wallpaper",
  "the other blue",
  "in the navy",
  "the",
  "wall",
  "john",
  "ugly",
  "olive drap", // typo? olive drab?
  "pale",
  "sfg",
  "caqui", // very likely khaki as very few seem relevant to the fruit
  "gurple",
  "smaragd", // emerald in other languages
  "ugly",
  "quartz fume", // originally was fumé, but wrong lang
  "disgusting",
  "v light blue",
  "rurple",
  "horrible",
  "jason",
  "green oscuro", // wrong lang
  "serious",
  "awesome",
  "not orange",
  "brains",
  "timmy",
  "boy",
  "nathan",
  "andrew",
  "betsy",
  "phyllis",
  "andy",
  "idfk",
  "triangle",
  "damnit",
  "depressed",
  "pistage",
  "pooh",
  "mage",
  "judy",
  "pista",
  "yelloq",
  "greej",
  "wha",
  "ggg",
  "aram",
  "horrifying",
  "led",
  "vomitus",
  "block",
  "loud",
  "nblue",
  "rachel",
  "pblue",
  "leela",
  "shi",
  "random",
  "very",
  "fear",
  "lie",
  "craig",
  "doom",
  "base",
  "yan",
  "eurgh",
  "jkl",
  "babies",
  "yucky",
  "pretty",
  "waffles",
  "tom",
  "obnoxious",
  "green duh",
  "tean",
  "baje",
  "help",
  "bland",
  "guam",
  "shut up",
  "monkey",
  "boops",
  "help me",
  "billy",
  "gtfo",
  "sgh",
  "deja vu",
  "tasty",
  "aweful",
  "qwe",
  "sdfa",
  "jill",
  "about",
  "underwear",
  "nfc",
  "redundant",
  "sandra",
  "daniel",
  "patricia",
  "tealert",
  "jhf",
  "pleasant",
  "funny",
  "ugg",
  "fat",
  "oral",
  "spindrift",
  "flurple",
  "ohra",
  "too bright",
  // "bright",
  "blude",
  "ight blue",
  "greenay",
  "ceal",
  "sadness",
  "nurple purple",
  "celean",
  "b blue",
  "insane",
  "urnge",
  "weird",
  "peacj",
  "agenta",
  "blus",
  "bolue",
  "pruble",
  "pinkis purple",
  "jennifer",
  "n a",
  "prius",
  "perfect",
  "boring",
  "ummm",
  "pink ew",
  "viol",
  "moron",
  "turchese",
  "indian",
  "these",
  "magen",
  "joseph",
  "lil",
  "rad",
  "harry",
  "gul",
  "old",
  "karkey",
  "oche",
  "maive",
  "tawn",
  "bye bye",
  "unnatural",
  "unpleasant",
  "putrid",
  "beautiful",
  "dirty",
  "strange",
  "death",
  "pew pew",
  "g g green",
  "0 0",
  "m m",
  "nm nm",
  "p p purple",
  "wu wu wu",
  "palish blue", // paleish ? palish?
  "boutros boutros ghali",
  "knock knock",
  "0 0 white",
  "darkk darkk purple",
  "weak putt putt",
  "po po",
  "not not blue",
  "ice ice baby",
  "un un pink",
  "255 255 255",
  "rgb00 60 60",
  "pinku pinku",
  "sky sky",
  "po po red",
  "laa laa",
  "and",
  "pred",
  "grayu",
  "too",
  "doing",
  "unfortunate",
  "pruce",
  "rorange",
  "nacy",
  "porange",
  "bred",
  "dreen",
  "marooned",
  "brellow", // is this supposed to be a portmanteau?
  "lav",
  "blay",
  "yorange",
  "yella",
  "pinki",
  "brue",
  "lils",
  "brink pink",
  "bleck",
  "rown",
  "purnk",
  "pupple",
  "somon",
  "yellos",
  "rood",
  "gray ey blue",
  "terd",
  "raddish", // redish or radish?
  "dark re",
  "peah",
  "peac",
  "dark rosa", // rose? rosa? pink?
  "appleblueseagreen",
  "ored",
  "blueis",
  "grye",
  "greu",
  "blew", // could be blue but don't want to pollute with other things
  "ourple",
  "azule",
  "purplse",
  "baise",
  "tellow",
  "bauge",
  "purper",
  "marrn",
  "granate",
  "lellow",
  "meow",
  "bob",
  "your mother",
  "really",
  "enough",
  "seriously",
  "undo last",
  "asian",
  "human",
  "never gonna give you up",
  "blur", // probably just blue
  "i cant tell",
  "rink", // not sure what this is about
  "ur mom",
  "odd",
  "bye",
  "pass",
  "ocra", // okra vs ochre?
  "painful",
  "grimace",
  "move", // ??
  "lavendel",
  "plink",
  "george",
  "liche", // probably lychee but who knows
  "no clue",
  "even gayer",
  "purple nurple",
  "omg",
  "wow",
  "eye cancer",
  "ow my eyes",
  "im drrockso betch",
  "1st april huh",
  "not quite red", // this one is ok but skews everything off
  "not green",
  "not sure",
  "over 9000",
  "dont know",
  "my eyes",
  "also ugly",
  "unsure",
  "my favorite color",
  "i dont know",
  "no idea",
  "its a jackal",
  "i wouldnt",
  "i hate you",
  "rick astley",
  "the game",
  "a color",
  "whatever",
  "im done",
  "not tubby",
  "too many",
  "i give up",
  "i have no idea",
  // mostly contributed by 1-2 users ////
  "raptor",
  "raptor flesh",
  "crux",
  "goluboy",
  "velociraptor",
  "89 camry maroon",
  "psychedelic aquamarine",
  "hipiness",
  "omygoodness",
  "gooseturd gray",
  "johnson o neely",
  "water flowing underground",
  "lwr",
  "over",
  "tlh",
  "viking",
  "int",
  "ggd",
  "lulz",
  "woeifj",
  "peins",
  "green wait yellow",
  "qwd",
  "ety",
  "maroon 3",
  "muffins",
  "reserved",
  "chertuse",
  "marzipanmarzipan",
  "marzipan marzipan",
  "green albastrui",
  "johnson o neely",
]);

for (let label of LLM_LABEL_SKIP) {
  SKIP_LABELS.add(label);
}

export const NON_CURSES = [
  // allow some of these, curate them after
  "poop",
  "poo",
  "nude",
  "bloody",
];

// // "homosexual purple", // todo: this should be curated out already
// // "faggy purple", // todo: already should be curated out, bug?
// // "homosexual pink", // todo: bug?
// // "homosexual", // todo: bug?

export const EXTRA_CURSES = [
  // actual curses
  "niger",
  "niggerkikefaggot",
  "dick",
  "buttsecks",
  "2girls1cup",
  "shit",
  "bitching",
  "dicks",
  "dickbutt",
  "cockballs",
  "cancerface",
  "dickbutts",
  "dicktits",
  "pimp",
  "dicks",
  "dickcunt",
  // 'scum', // maybe its OK
  // additional curses found by post-filtering
  "feces", // should we really skip this? is it a genuine color? lol
  "enema",
  "screw you",
  "preteen pink",
  "slutty lipstick",
  "injun",
  "my foreskin",
  "k screw it",
  "horse feces",
  "monkey feces brown",
  "feces green",
  "feces wine",
  "donkey punch bruise",
  "double penetration green",
  "fukin bright green",
  "pule",
  "preteen purple",
  "slutty red",
  "skanky eyeshadow blue",
  "strip club pink", // some of these could be genuine colors but will strip it.
  "slutty pink",
  "healthy feces",
  "unhealthy feces",
  "alien feces",
  "buttsex",
  "infant feces",
  "feces brown",
  "barbies wet dream",
  "you bastards",
  "green feces",
  "screw this",
  "hells blue",
  "skanky aqua",
  "screw it",
  "pr0n blue",
  "foreskin",
  "feces colored",
  "gayish feces colored",
  "blue you bastards",
  "booty call blue",
  "screw",
  "aww screw this",
  "kraut gray",
  "injun red",
  "babys feces",
  "strip club neon",
  "foreskin pink",
  "fresh feces brown",
  "puta",
  "golden shower yellow",
  "slutty purple pink",
  "bruised vajina",
  "simpson foreskin",
  "niggers",
  "hui",
  "baby feces",
  "screw this survey",
  "hells crotch",
  "mrs hells crotch",
  "kurac",
  "slutty",
  "penus",
  "perse",
  "faen",
  "screw you man",
  "pula calului",
  "light golden shower",
  "injun jewelry blue",
  "screw that",
  "chuj wie",
  "gnarly blue waffle",
  "ahole",
  "tub girl green",
  "tub girl yellow",
  "screw it all",
  "kurwa green",
  "spierdalaj ju",
  "skanky underwear pink",
  "screw you pink",
  "cockmaggot",
  "bitchass",
  "oh screw this",
  "fukken pink",
  "kurwa",
  "screw you green",
];

export const SUSPECT_TOKENS = new Set([
  "niger",
  "again",
  "shit",
  "dont",
  "know",
  "eek",
  "colors",
  "color", // "some color" etc..
  "colour",
  "colours",
  "bad",
  "eyes",
  "ow",
  "is",
  "lot",
  "no",
  "idea",
  "what",
  "to",
  "call",
  "even",
  "oh",
  "god",
  "hurts",
  "alas",
  "still",
  "i",
  "wouldnt",
  "isnt",
  "some",
  "dont",
  "know",
  "but",
  "like",
  "bring",
  "put",
  "you",
  "kill",
  "that",
  "wishes",
  "was",
  "thought",
  "fuck",
  "damn",
  "this",
  "never",
  "ends",
  "does",
  "lots",
  "same",
  "as",
  "minute",
  "ago",
  "please",
  "make",
  "stop",
  "f",
  "wish",
  "would",
  "have",
  "name",
  "im",
  "here",
  "end",
  "take",
  "slow",
  "longer",
  "wishing",
  "bad",
  "eat",
  "screw",
  "shit",
  "already",
  "had",
  "multiple",
  "when",
  "gaaa",
  "cant",
  "any",
  "more",
  "aaaahh",
  "burrnsss",
  "so",
  "begins",
  "looks",
  "just",
  "appears",
  "be",
  "again",
  "harder",
  "than",
  "nope",
  "wasnt",
  "last",
  "will",
  "jim",
  "stab",
  "till",
  "dies",
  "dunno",
  "now",
  "can",
  "go",
  "agh",
  "burns",
  "paste",
  "gonna",
  "thats",
  "done",
  "ill",
  "let",
  "my",
  "finish",
  "w",
  "tut",
  "yes",
  "spelled",
  "zomgaw",
  "ask",
  "eyes",
  "srsly",
  "turn",
  "id",
  "mark",
  "if",
  "get",
  "checked",
  "whatever",
  "called",
  "earlier",
  "keep",
  "going",
  "doesnt",
  "away",
  "seen",
  "okay",
  "its",
  "falling",
  "for",
  "word",
  "hugo",
  "think",
  "wrong",
  "sure",
  "yea",
  "one",
  "huh",
  "beeneth",
  "ok",
  "later",
]);

export const JUNK_VOWELLESS_OK = new Set([
  "html",
  "css",
  "tmnt",
  "http",
  "nypd",
  "marty",
  "ntsc",
  "mcfly",
  "cmyk",
  "gypsy",
  "lgbt",
  "ctrl",
  "lcd",
  "alt",
  "msdn",
  "mysql",
  "xckd",
]);

export const JUNK_TOKEN_ALLOWLIST = new Set([
  "lightsteelblue",
  "hooloovoo",
  "hoovooloo",
  "darkslateblue",
  "lightbulbs",
  "unsettlingly",
  "mediumslateblue",
  "lightslategray",
  "darkslategray",
  "mediumspringgreen",
  "grandparents",
  "unpleasantly",
  "nuggets",
  "delete",
  "another",
  "eggplants",
  "calling",
  "psych",
  "midsummer",
  "organic",
  "skys",
  "oldcastle",
  "oddparents",
  "lightgoldenrodyellow",
  "mcdonalds",
  "rorsach",
  "kfc",
  "starbucks",
  "sprng",
  "gren",
]);

// TODO:
export const TOKEN_ALLOW = new Set([
  "ugly green",
  "nice",
  "nasty",
  "rosé",
  "obnoxious",
  "pee green",
  "annoying",
  "light sea foam green",
  "yet",
  "some",
  "the",
  "bad green",
  "not quite red",
  "hookers",
  "hooker",
  "prince",
  "princess",
  "wall",
  "kermit",
  "john deere gree",
  "john",
  "cake",
  "oscar the grouch",
  "oscar",
  "breast cancer pink",
  "stop light green",
  "bad lipstick",
  "hooloovoo",
  "hot pants pink",
]);
