export const CURATE_MAX = 5000;

// export const LABEL_CURATE_SKIP = new Set([
//   "skinish",
//   "bogey",
//   "snotty",
//   "barf",
//   "vomit",
//   "bubonic",
//   "pukier",
//   "vomity",
//   "diarrhea",
//   "mucus",
//   "pukish",
//   "confederate",
//   'flesh',
//   "booger",
//   "pukey",
//   "diarrhea",
//   "lighter puke green",
//   "phlegm",
//   "doo doo brown",
//   "elf flesh",
//   "marijuana green",
//   "human flesh",
//   "white skin",
//   "throwup",
//   "baby barf",
//   "throwup green",
//   "caucasion",
//   "dark flesh tone",
//   "little girl pink",
//   "bright puke green",
//   "puke tan",
//   "caucasian flesh tone",
//   "dark skin tone",
//   "crayola flesh",
//   "vomit pink",
//   "barf brown",
//   "puke green brown",
//   "sick brown",
//   "pukish green",
//   "caucasian skin tone",
//   "dung",
//   "pus yellow",
//   "spew",
//   "pukey",
//   "poopy",
//   "rotting flesh",
//   "baby diarrhea",
//   "pus green",
//   "dark puke",
//   "scab",
//   "vomit orange",
//   "caucasian skin",
//   "puke purple",
//   "tanned flesh",
//   "poopy green",
//   "baby puke yellow",
//   "caucasian flesh",
//   "puke pink",
//   "pukey yellow",
//   "throw up green",
//   "puke green yellow",
//   "throw up",
//   "jaundice",
//   "spew green",
//   "puke yellow green",
//   "baby barf green",
//   "baby vomit green",
//   "pus",
//   "gangrene",
//   "poopy brown",
//   "barf yellow",
//   "dark puke green",
//   "dark skin",
//   "scab red",
//   "snot yellow",
//   "urine yellow",
//   "mucus green",
//   "mucus",
//   "diarrhea green",
//   "baby vomit",
//   "diarrhea brown",
//   "puke orange",
//   "pukey green",
//   "vomit brown",
//   "mold green",
//   "fleshy",
//   "flesh tone",
//   "dark flesh",
//   "urine",
//   "baby puke",
//   "booger",
//   "booger green",
//   "baby puke green",
//   "caucasian",
//   "barf green",
//   "puke brown",
//   "vomit yellow",
//   "diarrhea",
//   "flesh pink",
//   "snot",
//   "barf",
//   "skin tone",
//   "snot green",
//   "puke yellow",
//   "vomit green",
//   "flesh caucasian",
//   "vomit",
//   "puke",
//   "stripper pink",
//   "puke green",
//   "puss yellow",
//   "body",
//   "hippie green",
//   "red gore",
//   "gore red",
//   "flesh red",
//   "white man",
//   "puky green",
//   "placenta",
//   "congo blue",
//   "mustard gas",
//   "dark barf",
//   "toilet green",
//   "green puke",
//   "flesh tint",
//   "spew yellow",
//   "nude",
//   "baby poop green",
//   "baby poo green",
//   "baby poo",
//   "marijuana",
//   "poop",
//   "poo",
//   "poop brown",
//   "poo brown",
//   "piss yellow",
//   "turd",
//   "bloody",
// ]);

export function isFlagged(token) {
  if (LABEL_CURATE_EXACT_SKIP.has(token)) return true;
  if (LABEL_CURATE_SKIP.has(token)) return true;
  if (token.split(" ").some((n) => LABEL_CURATE_SKIP.has(n))) {
    return true;
  }
  return false;
}

export const LABEL_CURATE_EXACT_SKIP = new Set([
  "doo doo brown",
  "white man",
  "human flesh",
  "little girl pink",
  "throw up",
  "throw up green",
  "throw up yellow",
  "bloody stool",
  // a few that are more opinionated skips, these represent really poorly formed colors
  "not yellow",
  "nothing",
]);

export const LABEL_CURATE_SKIP = new Set([
  "skinish",
  "bogey",
  "snotty",
  "barf",
  "vomit",
  "bubonic",
  "pukier",
  "vomity",
  "diarrhea",
  "mucus",
  "skin",
  "flesh",
  "pukish",
  "confederate",
  "booger",
  "pukey",
  "puke",
  "phlegm",
  "marijuana",
  "throwup",
  "caucasion",
  "caucasian",
  "sick",
  "dung",
  "pus",
  "spew",
  "poopy",
  "scab",
  "jaundice",
  "gangrene",
  "red",
  "snot",
  "urine",
  "mold",
  "fleshy",
  "stripper",
  "puss",
  "body",
  "pee",
  "hippie",
  "hippy",
  "gore",
  "puky",
  "placenta",
  "congo",
  "gas",
  "toilet",
  "nude",
  "poop",
  "poo",
  "piss",
  "turd",
  "salmonella",
]);
